### ISSUE TITLE
Remove all references to Test1 on backend: BEGINNER ~ 10 minutes

### ISSUE THREAD

**Issue by adammenker** [adammenker/blindcs.com#23]
- Delete Test1 class
- Delete anything in BlindCsApplication class except for 

```
public static void main(String[] args) {
        SpringApplication.run(BlindcsApplication.class, args);
}
```

**Comment by frazie** [comment]
Hello,
I'd like to contribute to this

can I have it assigned to me

**Comment by adammenker** [comment]
> 

Yep, feel free to assign yourself any issues you would like to contribute on

**Comment by frazie** [comment]
Ok thank You.
